//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movie()
        {
            this.MovieTime = new HashSet<MovieTime>();
        }
    
        public int MovieID { get; set; }
        public string Name { get; set; }
        public string Actors { get; set; }
        public string Type { get; set; }
        public Nullable<double> Rate { get; set; }
        public string ImgUrl { get; set; }
        public Nullable<System.DateTime> ReleaseTime { get; set; }
        public string Intro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieTime> MovieTime { get; set; }
    }
}
