//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieTime
    {
        public int TimeID { get; set; }
        public Nullable<int> MovieID { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string Room { get; set; }
        public string RoomType { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Movie Movie { get; set; }
    }
}
