//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public int DetailID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> TimeID { get; set; }
        public Nullable<System.DateTime> Day { get; set; }
        public Nullable<int> Row { get; set; }
        public Nullable<int> Col { get; set; }
    }
}
