//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_APIMovieProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public Movie()
        {
            this.MovieTime = new HashSet<MovieTime>();
        }
    
        public int MovieID { get; set; }
        public string Name { get; set; }
        public string Actors { get; set; }
        public string Type { get; set; }
        public Nullable<double> Rate { get; set; }
        public string ImgUrl { get; set; }
        public Nullable<System.DateTime> ReleaseTime { get; set; }
        public string Intro { get; set; }
    
        public virtual ICollection<MovieTime> MovieTime { get; set; }
    }
}
