//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_APIMovieProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieTime
    {
        public int TimeID { get; set; }
        public Nullable<int> MovieID { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string Room { get; set; }
        public string RoomType { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Movie Movie { get; set; }
    }
}
