//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_APIMovieProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> TimeID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string MovieName { get; set; }
        public string ImgUrl { get; set; }
        public Nullable<int> Total { get; set; }
        public string Seat { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ReserveTime { get; set; }
        public string Room { get; set; }
    }
}
