//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_APIMovieProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tokens
    {
        public int TokenId { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
